### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by No1sBothered** [abjerner/Skybrud.Umbraco.Analytics#5]
The documentation says:

_Besides obtaining the OAuth credentials as described above, you'll also need to get a **refresh token** for your Google user, as well as the ID of the Analytics profile matching your site._ 

And from what i can tell that refresh token is manually added to the app settings

`<add key="SkybrudAnalytics.GoogleRefreshToken" value="Your refresh token" />`

Where does a google user find the refresh token, this process is not detailed in the documentation or described by google?

**Comment by abjerner** [comment]
Hi @markcasepilot,

When going for the single-site approach, it's assumed that you have this information for somewhere else. The thought with the single-site approach was that it might be a bit easier to set up - if you already had the necessary information. The same paragraph your quoted text is from, also suggests using the multi-site approach instead (it may still be used even if you only have a single site).

The multi-site approach on the other hand let's you enter information about your Google app/project, and then authenticate using your Google account. When you've successfully authenticated with Google this way, the refresh token will be saved in Umbraco for future use.

If you still wish to use the single-site approach, you can use the underlying [**Skybrud.Social.Google**](https://github.com/abjerner/Skybrud.Social.Google) and [**Skybrud.Social.Google.Analytics**](https://github.com/abjerner/Skybrud.Social.Google.Analytics) packages to set up your own authenticated. You can find a bit of information about that here:

https://social.skybrud.dk/google/authentication/

Hope that helps 😉

**Comment by No1sBothered** [comment]
Thanks

I took the multi-site approach and it all worked fine, nice work!

Thanks again
